# Generated by Django 5.0.14 on 2026-04-04 03:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=256)),
                ('track_uuid', models.CharField(max_length=36)),
                ('track_original_path', models.CharField(max_length=256)),
                ('track_date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_title', models.CharField(max_length=256)),
                ('track_artist', models.CharField(max_length=256)),
                ('track_album', models.CharField(max_length=256)),
                ('track_duration', models.FloatField()),
                ('track_minutes', models.IntegerField()),
                ('track_seconds', models.IntegerField()),
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.tracks')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(max_length=256)),
                ('playlist_type', models.CharField(choices=[('USER', 'user'), ('SYSTEM', 'system')], default='USER', max_length=12)),
                ('playlist_uuid', models.CharField(default=uuid.uuid4, max_length=36)),
                ('playlist_created_date', models.DateTimeField(auto_now_add=True)),
                ('tracks', models.ManyToManyField(to='api.tracks')),
            ],
        ),
    ]
