# Generated by Django 5.0.14 on 2026-04-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackinfo',
            name='track_minutes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='trackinfo',
            name='track_seconds',
            field=models.IntegerField(null=True),
        ),
    ]
