# Generated by Django 5.0.14 on 2026-04-20 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_trackinfo_track_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackinfo',
            name='track_minutes',
        ),
        migrations.RemoveField(
            model_name='trackinfo',
            name='track_seconds',
        ),
        migrations.AlterField(
            model_name='trackinfo',
            name='track',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trackinfo', to='api.tracks'),
        ),
    ]
