# Generated by Django 5.0.14 on 2026-04-21 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_trackinfo_track_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='trackinfo',
            name='track',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='trackinfo', serialize=False, to='api.tracks'),
        ),
    ]
